name: VSCE

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
        
    pull_request:
        branches: [ "main" ]

jobs:
    package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - run: npm install -g @vscode/vsce 

            - run: vsce package

            - uses: actions/upload-artifact@v4
              with:
                path: "*.vsix"
